services:
  db:
    image: postgres:16
    container_name: pgdb
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-glic-db}
      POSTGRES_USER: ${POSTGRES_USER:-glic-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-glic-password}
    ports:
      - "${PORT_DB:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U glic-user -d glic-db"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
